### ISSUE TITLE
Heads up: PyPI is dropping support for bdist_wininst

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.wineggbuilder#10]
See https://mail.python.org/pipermail/distutils-sig/2016-September/029624.html:

> This means that:
> - supported sdist types will be reduced to .tar.gz and .zip
> - projects will need to choose one or the other for future releases
> - **supported binary formats will be reduced to bdist_wheel and bdist_egg**

AFAICT everything currently builds both bdist_egg and bdist_wininst with one exception: `lxml` builds only bdist_wininst.  `lxml` builds appear to be broken anyway -- PyPI's last release ([3.6.4](https://pypi.python.org/pypi/lxml/3.6.4)) has no binary Windows packages whatsoever.  ([lxml 3.6.0](https://pypi.python.org/pypi/lxml/3.6.0) had both bdist_wininst and bdist_wheel releases for Windows.)

**Comment by agroszer** [comment]
sigh

As it looks it's not hard to convert an egg or wininst to a wheel

I'm just badly missing time to add that to wineggbuilder

**Comment by jamadden** [comment]
Correct me if I'm wrong, please: pypi eggs are only used by buildout on Windows, at least by default? At least that's the impression I've been laboring under for the projects I maintain (e.g. gevent). And wheels seem to be the most popular download, given their relative recent introduction. 

My organization uses buildout extensively, but only on Linux and OS X, so sdists have only been of use to us (except for local testing); wheels would be nice eventually, and it seems discussions are progressing in that area. 

If I've missed something and should have helped speak up, I'm sorry.

**Comment by mgedmin** [comment]
> Correct me if I'm wrong, please: pypi eggs are only used by buildout on Windows, at least by default? 

buildout *and* easy_install, which matters when you try to pip install something that has e.g. setup_requires=['persistent']

zope.wineggbuilder builds only eggs (and exe installers [for some reason](https://github.com/zopefoundation/zope.wineggbuilder/issues/1)) because it was set up before wheels even existed.  There's desire to have it build wheels too (see #2), but *sigh* you know how it is with overworked people and/or burnout.

**Comment by tseaver** [comment]
The winbot host is decommissioned.  We've decided to switch to publishing Windows wheels via Appveyor.
