### ISSUE TITLE
Build binary wheels for Windows

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.wineggbuilder#2]
I once hijacked the comments of bug #1 to request wheel files.  Since it's not nice to hijack existing bugs I decided to file a new one.

My desire for wheels is increasing, now that I have a Windows VM on Rackspace that cannot download anything from PyPI due to [mysterious SSL errors](https://gist.github.com/mgedmin/7637559).  pip doesn't suffer from the SSL download issues, but it needs wheels for binary packages.

I see there's a `wheel convert` command that can take a bdist_wininst installer and produce a wheel file.

I have commit access to zope.wineggbuilder and rdesktop access to winbot.zope.org, which means that in theory I'm capable of implementing and testing this myself.  I intend to try when I can find enough spare time.

**Comment by techtonik** [comment]
So, what is the progress on this?

**Comment by pombredanne** [comment]
@techtonik as far as I am concerned, my patch was pulled in long ago by @dholth and wheel can build a .whl from an installed buildout egg.  https://bitbucket.org/pypa/wheel/commits/all?search=pom 
So the case is closed for my use case.

**Comment by mgedmin** [comment]
AFAIK there's been no progress on this.

**Comment by mgedmin** [comment]
I added an appveyor.yml to zope.interface that builds wheels, using the instructions at http://python-packaging-user-guide.readthedocs.org/en/latest/appveyor/.

It would certainly be possible to encrypt PyPI credentials and have appveyor upload the build wheel files when it's building release tags:
- http://www.appveyor.com/docs/build-configuration#secure-variables
- http://www.appveyor.com/docs/branches#build-on-tags-github-only

I don't know if it's possible to ask Appveyor to force-build older release tags, especially when those don't have an appveyor.yml.

**Comment by mgedmin** [comment]
All the modules I care about now have Appveyor configs that build and upload Windows wheels to PyPI.

Here's how you can check which ZopeFoundation packages have C extension modules but don't have wheels:

```
mkdir -p ~/src/zopefoundation && cd ~/src/zopefoundation
ghcloneall --org ZopeFoundation  # https://pypi.python.org/pypi/ghcloneall
find -name '*.c' | cut -d / -f 2 | sort -u > have-modules.txt
grep -l twine ./*/appveyor.yml | cut -d / -f 2 | sort -u > have-wheels.txt
comm -23 have-modules.txt have-wheels.txt > missing-wheels.txt
```

Currently these are

```
AccessControl
Acquisition
ExtensionClass
initgroups
Persistence
zc.FileStorage
```

Adding wheel support to them shouldn't be too difficult -- follow the checklist in, e.g., https://github.com/zopefoundation/zodbpickle/issues/23.  I currently have no plans to do so.

**Comment by tseaver** [comment]
Thanks, @mgedmin, for the research / summary.

FWIW, the winbot host is already decommissioned, which makes any further work on this project a bit moot.

I've opened issues for those projects:

- https://github.com/zopefoundation/AccessControl/issues/47
- https://github.com/zopefoundation/Acquisition/issues/24
- https://github.com/zopefoundation/ExtensionClass/issues/19
- https://github.com/zopefoundation/initgroups/issues/1
- https://github.com/zopefoundation/Persistence/issues/8
- https://github.com/zopefoundation/zc.FileStorage/issues/1

**Comment by mgedmin** [comment]
> FWIW, the winbot host is already decommissioned, which makes any further work on this project a bit moot.

Ha!  It's why I finally got off my butt and added Appveyor files to the last few packages that were zodbbrowser's dependencies -- no new Windows eggs meant my wheel-conversion hack stopped working and my Jenkins started complaining.  :)
