### ISSUE TITLE
python 3.3 support missing

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/zope.wineggbuilder#3]
At the moment zope.wineggbuilder is building binary packages for Python 2.6, 2.7, 3.1, and 3.2.  It should also be building them for 3.3.

According to https://github.com/zopefoundation/zope.wineggbuilder/issues/1#issuecomment-15760600 a backup of the Rackspace VM blocks this, for quite a while.

**Comment by mgedmin** [comment]
I think this is fixed?  I haven't checked all packages, but I see zope.interface has eggs for 3.3.

**Comment by agroszer** [comment]
for eggs yes, lxml is not yet

**Comment by techtonik** [comment]
@agroszer why lxml uses some eggbuilder and not some wheelbuilder anyway?

**Comment by tseaver** [comment]
The winbot host is decommissioned.  We've decided to switch to publishing Windows wheels via Appveyor.
