### ISSUE TITLE
compile/build errors should not pass silently

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/zope.wineggbuilder#4]
The problem is that if a package build (right now lxml) fails, it passes silently.
Someone has to figure from other failing builds that the .exe/.egg is missing from pypi.

But what's the right solution?
The problem is that the build runs every 30 mins or so, emailing someone about a failure every 30 mins would be a pain.

**Comment by tseaver** [comment]
The winbot host is decommissioned.  We've decided to switch to publishing Windows wheels via Appveyor.
