### ISSUE TITLE
Fix build of libxml2 2.9.4 for lxml

### ISSUE THREAD

**Issue by scoder** [zopefoundation/zope.wineggbuilder#9]
I don't know how difficult it is to apply patches as part the build, but there is a small patch that should enable building the latest libxml2 version: https://mail.gnome.org/archives/xml/2016-June/txtPGtRYn45yN.txt
If it's too much effort (or too much one-time complexity), waiting for the next release of libxml2 would be fine, obviously.

**Comment by tseaver** [comment]
First, I'm not sure I understand -- can you be clearer about what the breakage was?  I.e., provide a copy of the command line and error?

Second, the current version of `lxml` is 3.6.1 (just [released](https://pypi.python.org/pypi/lxml/3.6.1) today), does not yet have  Windows builds (probably in progress tonight).  [lxml 3.6.0](https://pypi.python.org/pypi/lxml/3.6.0) has MSIs, Windows wheels, and Windows eggs built.  Is there some reason you can't upgrade?

**Comment by scoder** [comment]
Ah, sorry. I was referring to this commit: dac3fb70a5ab2cbe7f8ebde985ef95deadf68e14

I don't have the problem myself and I didn't see any failure output, but my guess was that the patch above would fix it because others tried to build libxml2 on Windows and that was the problem they ran into, according to their mailing list.

**Comment by agroszer** [comment]
Yeah I tried to use the lastest libs... I'm sorry I'm under water nowadays regarding work, so I'll rather wait for the next release.

**Comment by scoder** [comment]
No problem. I sort-of guessed that that might be the case, just wanted to leave a note that there is a fix available. I'll close the issue.
